import Head from 'next/head';
import styles from '../styles/Home.module.css';
import type { ReactElement } from 'react';
import { AppLayout,HeaderLayout } from 'components/layout';
import type {NextPageWithLayout} from "./_app"
const Home: NextPageWithLayout = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          안녕하세요 <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <p className={styles.description}>
          중첩 레이아웃 적용 완료!
        </p>
      </main>
    </div>
  );
};
Home.getLayout = function getLayout(page: ReactElement) {
  return (
    <AppLayout>
      <HeaderLayout>{page}</HeaderLayout>
    </AppLayout>
  );
};

export default Home;
