import Head from 'next/head';
import styled, { keyframes } from 'styled-components';
import type { ReactElement } from 'react';
import type { NextPageWithLayout } from './_app';
import { AppLayout } from 'components/layout';
import Router from 'next/router';
const Page: NextPageWithLayout = () => {


  const KAKAO_AUTH_URL = `https://kauth.kakao.com/oauth/authorize?client_id=${process.env.NEXT_PUBLIC_KAKAO_CLIENT_ID}&redirect_uri=${process.env.NEXT_PUBLIC_KAKAO_REDIRECT_URI}&response_type=code`;
  
  const goKakaoLogin = () => {
    Router.push(KAKAO_AUTH_URL);
  };
  // 임시 디자인 입니다! 피그마 보고 여차저차 따라했어유 ... 
  return (
    <div>
      <Head>
        <title>Catch Me !!! </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Wrapper>
          <MainContainer>
            <Title>CATCH ME !</Title>
            <SubTitle>
              로그인 <strong>1</strong>초컷 하고 <br />
              <strong>나만의 퀴즈</strong>를 만들어보세요!
            </SubTitle>
            <KakaoLoginBtn onClick={goKakaoLogin}>
              <img src={'/assets/img/kakao_icon.png'} />
              <span>카카오로 시작하기</span>
            </KakaoLoginBtn>
          </MainContainer>
        </Wrapper>
      </main>
    </div>
  );
};
Page.getLayout = function getLayout(page: ReactElement) {
  return <AppLayout>{page}</AppLayout>;
};

const bounce = keyframes` 
  0% {transform: translatey(0px);}
  100% {transform: translatey(-10px);}
`;

const Wrapper = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100vh;
  background-color: #9437ff;
`;
const MainContainer = styled.div`
  background-color: white;
  border-radius: 30px;
  display: flex;
  position: relative;
  flex-direction: column;
  align-items: center;
  justify-content: space-between;
  padding: 10% 5% 10% 5%;
  height: 60%;
`;
const Title = styled.div`
  animation: ${bounce} 0.3s linear 0s infinite alternate;
  font-weight: bold;
  font-size: 50px;
  color: white;
  text-shadow: -2px 0 #9437ff, 0 2px #9437ff, 8px 0 #9437ff, 0 -8px #9437ff;
  padding: 1rem 0 1rem 0;
`;
const SubTitle = styled.div`
  font-size: 18px;
  font-weight: bold;
  text-align: center;
  strong {
    color: #9437ff;
  }
`;
const KakaoLoginBtn = styled.button`
  position: relative;
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 0 30px;
  border-radius: 30px;
  height: 50px;
  background-color: #FBE54D;
  border: none;
  &:hover {
    cursor: pointer;
  }
  & img {
    position: relative;
    width: 18px;
    height: 17px;
    margin-right: 20px;
  }
  & span {
    font-weight: bold;
    color: #391C1C;
  }
`;


export default Page;
